site_name: Vargur API SDK
theme:
  name: material
  custom_dir: docs/overrides
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.top
    - search.suggest
    - search.highlight
  palette:
    - scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode
    - scheme: slate
      primary: indigo
      accent: indigo
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode

plugins:
  - search
  - i18n:
      default_language: en
      languages:
        en: English
        ko: 한국어
  - git-revision-date-localized:
      type: date
      fallback_to_build_date: true
  - minify:
      minify_html: true

markdown_extensions:
  - pymdownx.highlight
  - pymdownx.superfences
  - admonition
  - toc:
      permalink: true

extra:
  version:
    provider: mike

nav:
  - Home: index.md
  - User Guide: user-guide.md
  - API Reference: api-reference.md
  - Plugin Guidelines: plugin-guidelines.md

extra_css:
  - stylesheets/extra.css
