name: Publish Vargur SDK and Docs

on:
  push:
    branches:
      - release
    tags:
      - 'v*'
  release:
    types: [created]

permissions:
  contents: write
  id-token: write

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0  # 전체 git 히스토리를 가져옵니다 (setuptools_scm에 필요)

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -e .
        pip install mkdocs mkdocs-material mkdocs-git-revision-date-localized-plugin mkdocs-i18n mkdocs-minify-plugin setuptools_scm

    - name: Build and publish to PyPI
      if: github.event_name == 'release'
      env:
        TWINE_USERNAME: ${{ secrets.PYPI_USERNAME }}
        TWINE_PASSWORD: ${{ secrets.PYPI_PASSWORD }}
      run: |
        pip install wheel twine
        python setup.py sdist bdist_wheel
        twine check dist/*
        twine upload dist/*

    - name: Build MkDocs documentation
      run: |
        mkdocs build --site-dir ./site

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v4
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./site
        force_orphan: true
