name: Publish Vargur SDK and Docs

on:
  push:
    branches:
      - release
      - develop
    tags:
      - 'v*'
  release:
    types: [created]

permissions:
  contents: write
  id-token: write

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install poetry
        poetry install
        poetry add mkdocs mkdocs-material mkdocs-git-revision-date-localized-plugin mkdocs-i18n mkdocs-minify-plugin

    - name: Build and publish to PyPI
      if: github.event_name == 'release'
      env:
        PYPI_USERNAME: ${{ secrets.PYPI_USERNAME }}
        PYPI_PASSWORD: ${{ secrets.PYPI_PASSWORD }}
      run: |
        poetry config pypi-token.pypi $PYPI_PASSWORD
        poetry build
        poetry publish

    - name: Build MkDocs documentation
      run: |
        poetry run mkdocs build --site-dir ./site

    - name: Preserve CNAME
      run: |
        if [ -f "CNAME" ]; then
          cp CNAME ./site/
        fi

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v4
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./site
        force_orphan: true
        cname: ${{ secrets.CUSTOM_DOMAIN }}
